#!/bin/bash



CFGFILE="${MEDIADIR}/config/plugin.fpp-VSAImport"
getSetting() {
    SETTING=$1
    if [ -f "${CFGFILE}" ]; then
        if [ -f "/usr/bin/flock" ]; then
            exec {FD}<$CFGFILE
            flock -n ${FD} || exit 1
            grep -i --binary-files=text "^${SETTING}\s*=.*" ${CFGFILE} | sed -E -e "s/^${SETTING}\s*=\s*(.*)/\1/" -e 's/"//g'
            flock -u ${FD}
        else
            grep -i --binary-files=text "^${SETTING}\s*=.*" ${CFGFILE} | sed -E -e "s/^${SETTING}\s*=\s*(.*)/\1/" -e 's/"//g'
        fi
    fi
}



EXTRAFLAGS=
if [ -f $CFGFILE ]; then
    USEPWM=$(getSetting VSAUsePWMConfig)
    if [ "${USEPWM}" == "1" ]; then
        EXTRAFLAGS="-p "
    fi
fi

/home/fpp/media/plugins/fpp-VSAImport/bin/vsa-utils $EXTRAFLAGS -j "$1"
